# Architecture identifier.
arch = "aarch64"
# Platform identifier.
platform = "aarch64-bsta1000b"
# Platform family.
family = "aarch64-bsta1000b"

# Base address of the whole physical memory.
#phys-memory-base = "0x0020_0000"
phys-memory-base = "0x0040_0000"
# 2G Size of the whole physical memory.
phys-memory-size = "0x4000_0000"
# Base physical address of the kernel image.
kernel-base-paddr = "0x0048_0000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_0048_0000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_0000_0000_0000"
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    ["0xfeb50000", "0x1000"], # uart8250
    ["0xfe600000", "0x20000"], # arm,gic-v3
    ["0xfe680000", "0x100000"], # arm,gic-v3
    ["0xfe180000", "0x10000"], # rockchip,rk3588-pcie
    ["0xfe190000", "0x10000"], # rockchip,rk3588-pcie
]

virtio-mmio-regions = []

# Base physical address of the PCIe ECAM space.
# pci-ecam-base = "0x40_1000_0000"
# End PCI bus number (`bus-range` property in device tree).
# pci-bus-end = "0xff"
# PCI device memory ranges (`ranges` property in device tree).
# pci-ranges = []

# UART Address
uart-paddr = "0xfeb50000"
# UART irq from device tree
uart-irq = "0x14d"
# GICD Address
gicd-paddr = "0xfe600000"
# GICC Address
gicc-paddr = "0xfe610000"
# GICR Address of rk3588
gicr-paddr = "0xfe680000"

# PSCI
psci-method = "smc" # arm,psci-1.0
