# Architecture identifier.
arch = "aarch64"
# Platform identifier.
platform = "bsta1000b-fada-aarch64"

# Base address of the whole physical memory.
phys-memory-base = "0x80000000"
# Size of the whole physical memory.
phys-memory-size = "0x70000000"
# Base physical address of the kernel image.
kernel-base-paddr = "0x81000000"
# Base virtual address of the kernel image.
kernel-base-vaddr = "0xffff_0000_8100_0000"
# Linear mapping offset, for quick conversions between physical and virtual
# addresses.
phys-virt-offset = "0xffff_0000_0000_0000"
# MMIO regions with format (`base_paddr`, `size`).
mmio-regions = [
    ["0x20008000", "0x1000"], # uart8250 UART0
    ["0x32000000", "0x8000"], # arm,gic-400
]

virtio-mmio-regions = []

# Base physical address of the PCIe ECAM space.
# pci-ecam-base = "0x40_1000_0000"
# End PCI bus number (`bus-range` property in device tree).
# pci-bus-end = "0xff"
# PCI device memory ranges (`ranges` property in device tree).
# pci-ranges = []

# UART Address
uart-paddr = "0x20008000"
uart-irq-num = "213"
# GICD Address
gicd-paddr = "0x32001000"
# GICC Address
gicc-paddr = "0x32002000"
